Add pip cache to test jobs
Signed-off-by: Wade Barnes <wade@neoterictech.ca>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -192,96 +192,112 @@ jobs:
           mkdir -p ${GITHUB_WORKSPACE}/cache
           touch ${GITHUB_WORKSPACE}/cache/${{ env.CACHE_KEY_LINT }}
 
-  # indy_plenum_tests:
-  #   name: Sliced Module Tests
-  #   # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
-  #   needs: [workflow-setup, build-image]
-  #   runs-on: ubuntu-20.04
-  #   # Fix for scacap/action-surefire-report out of memory error:
-  #   # - https://github.com/ScaCap/action-surefire-report/issues/17
-  #   env:
-  #     NODE_OPTIONS: '--max_old_space_size=4096'
-  #   container:
-  #     image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-build
-  #   strategy:
-  #     matrix:
-  #       module: [plenum]
-  #       # To slice up the tests into smaller chunks add additional sequential
-  #       # numbers here.  The subsequent steps will adjust automatically.
-  #       # ${{ strategy.job-total }} is used to get the total number of slices.
-  #       slice: [1, 2, 3, 4, 5, 6, 7, 8]
-  #     fail-fast: false
-  #   steps:
-  #     - name: Check out code
-  #       uses: actions/checkout@v2
+  indy_plenum_tests:
+    name: Sliced Module Tests
+    # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
+    needs: [workflow-setup, build-image]
+    runs-on: ubuntu-20.04
+    # Fix for scacap/action-surefire-report out of memory error:
+    # - https://github.com/ScaCap/action-surefire-report/issues/17
+    env:
+      NODE_OPTIONS: '--max_old_space_size=4096'
+    container:
+      image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-build
+    strategy:
+      matrix:
+        module: [plenum]
+        # To slice up the tests into smaller chunks add additional sequential
+        # numbers here.  The subsequent steps will adjust automatically.
+        # ${{ strategy.job-total }} is used to get the total number of slices.
+        slice: [1, 2, 3, 4, 5, 6, 7, 8]
+      fail-fast: false
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
 
-  #     - name: Install dependencies
-  #       run: pip install .[tests]
+      - name: Check Pip Cache
+        uses: actions/cache@v2
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
 
-  #     - name: Run Indy Plenum ${{ matrix.module }} test slice ${{ matrix.slice }}/${{ strategy.job-total }}
-  #       id: plenum-test
-  #       run: RUSTPYTHONASYNCIODEBUG=0 python3 runner.py --pytest "python3 -m pytest -l -vv" --dir "${{ matrix.module }}" --output "test-result-plenum-${{ matrix.slice }}.txt" --test-only-slice "${{ matrix.slice }}/${{ strategy.job-total }}"
+      - name: Install dependencies
+        run: pip install .[tests]
 
-  #     - name: Publish Test Report
-  #       if: success() || failure()
-  #       uses: scacap/action-surefire-report@v1.0.7
-  #       continue-on-error: true
-  #       with:
-  #         check_name: Indy Plenum ${{ matrix.module }} Test Report for slice ${{ matrix.slice }}/${{ strategy.job-total }}
-  #         github_token: ${{ secrets.GITHUB_TOKEN }}
-  #         report_paths: "*-test-results.xml"
+      - name: Run Indy Plenum ${{ matrix.module }} test slice ${{ matrix.slice }}/${{ strategy.job-total }}
+        id: plenum-test
+        run: RUSTPYTHONASYNCIODEBUG=0 python3 runner.py --pytest "python3 -m pytest -l -vv" --dir "${{ matrix.module }}" --output "test-result-plenum-${{ matrix.slice }}.txt" --test-only-slice "${{ matrix.slice }}/${{ strategy.job-total }}"
 
-  #     - name: Upload Detailed Test Failure Results
-  #       # The test runner only emits the detailed test results if the tests fail.
-  #       if: (steps.plenum-test.outcome == 'failure') && failure()
-  #       uses: actions/upload-artifact@v2
-  #       with:
-  #         name: detailed-test-result-slice-${{ matrix.slice }}
-  #         path: test-result-plenum-${{ matrix.slice }}.txt
-  #         retention-days: 5
+      - name: Publish Test Report
+        if: success() || failure()
+        uses: scacap/action-surefire-report@v1.0.7
+        continue-on-error: true
+        with:
+          check_name: Indy Plenum ${{ matrix.module }} Test Report for slice ${{ matrix.slice }}/${{ strategy.job-total }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          report_paths: "*-test-results.xml"
 
-  # indy_plenum_module_tests:
-  #   name: Module Tests
-  #   # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
-  #   needs: [workflow-setup, build-image]
-  #   runs-on: ubuntu-20.04
-  #   container:
-  #     image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-build
-  #   strategy:
-  #     matrix:
-  #       module: [common, crypto, ledger, state, storage, stp_core, stp_zmq]
-  #     fail-fast: false
-  #   steps:
-  #     - name: Check out code
-  #       uses: actions/checkout@v2
+      - name: Upload Detailed Test Failure Results
+        # The test runner only emits the detailed test results if the tests fail.
+        if: (steps.plenum-test.outcome == 'failure') && failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: detailed-test-result-slice-${{ matrix.slice }}
+          path: test-result-plenum-${{ matrix.slice }}.txt
+          retention-days: 5
 
-  #     - name: Install dependencies
-  #       run: pip install .[tests]
+  indy_plenum_module_tests:
+    name: Module Tests
+    # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
+    needs: [workflow-setup, build-image]
+    runs-on: ubuntu-20.04
+    container:
+      image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-build
+    strategy:
+      matrix:
+        module: [common, crypto, ledger, state, storage, stp_core, stp_zmq]
+      fail-fast: false
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
 
-  #     - name: Run Indy Plenum ${{ matrix.module }} tests
-  #       run: python3 -m pytest -l -vv --junitxml=test-result-plenum-${{ matrix.module }}.xml ${{ matrix.module }}
+      - name: Check Pip Cache
+        uses: actions/cache@v2
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
 
-  #     - name: Publish Test Report
-  #       uses: scacap/action-surefire-report@v1.0.7
-  #       continue-on-error: true
-  #       with:
-  #         check_name: Indy Plenum ${{ matrix.module }} Test Report
-  #         github_token: ${{ secrets.GITHUB_TOKEN }}
-  #         report_paths: test-result-plenum-${{ matrix.module }}.xml
+      - name: Install dependencies
+        run: pip install .[tests]
 
-  # lint:
-  #   name: Lint
-  #   # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
-  #   needs: [workflow-setup, lint-image]
-  #   runs-on: ubuntu-20.04
-  #   container:
-  #     image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-lint
-  #   steps:
-  #     - name: Check out code
-  #       uses: actions/checkout@v2
+      - name: Run Indy Plenum ${{ matrix.module }} tests
+        run: python3 -m pytest -l -vv --junitxml=test-result-plenum-${{ matrix.module }}.xml ${{ matrix.module }}
 
-  #     - name: flake8
-  #       run: python3 -m flake8
+      - name: Publish Test Report
+        uses: scacap/action-surefire-report@v1.0.7
+        continue-on-error: true
+        with:
+          check_name: Indy Plenum ${{ matrix.module }} Test Report
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          report_paths: test-result-plenum-${{ matrix.module }}.xml
+
+  lint:
+    name: Lint
+    # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
+    needs: [workflow-setup, lint-image]
+    runs-on: ubuntu-20.04
+    container:
+      image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-lint
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
+
+      - name: flake8
+        run: python3 -m flake8
 
   # build_release:
   #   name: Build Release
